### ISSUE TITLE
create integration branch

### ISSUE THREAD

**Issue by kishorliv** [sharma66mahesh/ShadowShift#5]
I think it is a good practice to have integration branch(eg: "develop") when more than one developer is contributing to the project. Its good if every code change goes through a pull request and review process.
Also, will be super beneficial when we start releasing this app to the web store. Without the integration branch, every commit to main will probably change the released app.

**Comment by sharma66mahesh** [comment]
Yeah - that's right. 
All the PRs should come to the develop branch - tested there and then if everything's fine, it will be merged into main with a specific tag/version.
